services:
  backend:
    build: ./backend
    container_name: nestjs-backend
    ports:
      - "3000:3000"
    env_file:
      - ./backend/.env 
    

  frontend:
    build: ./frontend
    container_name: vite-frontend
    command: ["npm", "run", "dev", "--", "--host", "0.0.0.0"]
    ports:
      - "5173:5173"
    env_file:
      - ./frontend/.env 
    depends_on:
      - backend

  

volumes:
  mongo-data:
