# Use official Node.js image
FROM node:20

# Set working directory
WORKDIR /app

# Copy package.json and install dependencies
COPY package.json package-lock.json ./
RUN npm install

# Copy the rest of the application
COPY . .

# Expose backend port
EXPOSE 3000

# Start the NestJS application
CMD ["npm", "run", "start"]
